kind: pipeline
name: default

steps:
- name: publish
  image: plugins/npm
  settings:
    username: i5o
    password:
      from_secret: npm_password
    email: ignacio@ole.org
  when:
    event:
    - tag
